#!/usr/bin/env bash
set -e

OPTIONS_FILE="options.env"

echo "=== Building options.env ==="

# Helper function for Y/n prompts → true/false with default
prompt_bool() {
    local prompt="$1"
    local default="$2"
    local answer
    local result
    while :; do
        if [[ "$default" == "true" ]]; then
            read -r -p "$prompt ([Y]/n, default Y): " answer
            answer="${answer:-Y}"
        else
            read -r -p "$prompt ([y]/N, default N): " answer
            answer="${answer:-N}"
        fi

        case "${answer,,}" in
            y|yes) result="true"; break ;;
            n|no)  result="false"; break ;;
            true|false) result="$answer"; break ;;
            *) echo "Please answer y or n." ;;
        esac
    done
    echo "$result"
}

# 1. PIA Port Forwarding
PIA_PF=$(prompt_bool "Enable PIA port forwarding?" "true")

# 2. VPN Protocol
VPN_PROTOCOL="wireguard"  # default
USE_OPENVPN=$(prompt_bool "Use OpenVPN instead of WireGuard?" "false")
if [[ "$USE_OPENVPN" == "true" ]]; then
    echo "Select OpenVPN variant:"
    vpn_options=(
        "openvpn_udp_standard"
        "openvpn_udp_strong"
        "openvpn_tcp_standard"
        "openvpn_tcp_strong"
    )

    select vpn_choice in "${vpn_options[@]}"; do
        if [[ -n "$vpn_choice" ]]; then
            VPN_PROTOCOL="$vpn_choice"
            break
        else
            echo "Invalid selection. Enter a number 1-${#vpn_options[@]}."
        fi
    done
fi

# Force WireGuard if port forwarding is enabled
if [[ "$PIA_PF" == "true" ]]; then
    echo "PIA port forwarding requires WireGuard. Forcing VPN_PROTOCOL=wireguard"
    VPN_PROTOCOL="wireguard"
fi

# 3. Auto-connect
AUTOCONNECT=$(prompt_bool "Enable auto-connect to server?" "false")

# 4. Disable IPv6
DISABLE_IPV6=$(prompt_bool "Disable IPv6?" "true")

# 5. PIA DNS
PIA_DNS=$(prompt_bool "Force PIA DNS?" "true")

# 6. Dedicated IP token
read -r -p "Enter dedicated IP token (DIP####...) or leave blank for none: " dip
DIP_TOKEN="${dip:-none}"

# 7. Preferred region (dependent on AUTOCONNECT)
if [[ "$AUTOCONNECT" == "true" ]]; then
    PREFERRED_REGION="none"
else
    read -r -p "Enter preferred region (or leave blank for none): " pref
    PREFERRED_REGION="${pref:-none}"
fi

# Write to options.env
cat > "$OPTIONS_FILE" <<EOF
# Auto-generated by build_options.sh
PIA_PF=$PIA_PF
VPN_PROTOCOL=$VPN_PROTOCOL
AUTOCONNECT=$AUTOCONNECT
DISABLE_IPV6=$DISABLE_IPV6
PIA_DNS=$PIA_DNS
DIP_TOKEN=$DIP_TOKEN
PREFERRED_REGION=$PREFERRED_REGION
EOF

echo "options.env created successfully:"
cat "$OPTIONS_FILE"