#!/usr/bin/env bash
set -e

OPTIONS_FILE="options.env"

echo "=== Building options.env ==="

# Helper function for Y/n prompts → true/false with default
prompt_bool() {
    local prompt="$1"
    local default="$2"
    local answer
    local result
    while :; do
        read -r -p "$prompt ([Y]es/[n]o, default $default): " answer
        answer="${answer:-$default}"
        case "${answer,,}" in
            y|yes) result="true"; break ;;
            n|no)  result="false"; break ;;
            true|false) result="$answer"; break ;;
            *) echo "Please answer Y or n." ;;
        esac
    done
    echo "$result"
}

# 1. AUTOCONNECT
AUTOCONNECT=$(prompt_bool "Enable auto-connect to server?" "false")

# 2. VPN_PROTOCOL
# Default to WireGuard
VPN_PROTOCOL="wireguard"

# If user wants OpenVPN, show menu
USE_OPENVPN=$(prompt_bool "Use OpenVPN instead of WireGuard?" "false")
if [[ "$USE_OPENVPN" == "true" ]]; then
    echo "Select OpenVPN variant:"
    vpn_options=(
        "openvpn_udp_standard"
        "openvpn_udp_strong"
        "openvpn_tcp_standard"
        "openvpn_tcp_strong"
    )

    select vpn_choice in "${vpn_options[@]}"; do
        if [[ -n "$vpn_choice" ]]; then
            VPN_PROTOCOL="$vpn_choice"
            break
        else
            echo "Invalid selection. Enter a number 1-${#vpn_options[@]}."
        fi
    done
fi

# 3. PIA_PF
PIA_PF=$(prompt_bool "Enable PIA port forwarding?" "true")

# If port forwarding is enabled, force WireGuard
if [[ "$PIA_PF" == "true" ]]; then
    echo "PIA port forwarding requires WireGuard. Forcing VPN_PROTOCOL=wireguard"
    VPN_PROTOCOL="wireguard"
fi

# 4. DISABLE_IPV6
DISABLE_IPV6=$(prompt_bool "Disable IPv6?" "true")

# 5. PREFERRED_REGION
if [[ "$AUTOCONNECT" == "true" ]]; then
    PREFERRED_REGION="none"
else
    read -r -p "Enter preferred region (or leave blank for none): " pref
    PREFERRED_REGION="${pref:-none}"
fi

# 6. PIA_DNS
PIA_DNS=$(prompt_bool "Force PIA DNS?" "true")

# 7. DIP_TOKEN
read -r -p "Enter dedicated IP token (DIP####...) or leave blank for none: " dip
DIP_TOKEN="${dip:-none}"

# Write to options.env
cat > "$OPTIONS_FILE" <<EOF
# Auto-generated by build_options.sh
AUTOCONNECT=$AUTOCONNECT
VPN_PROTOCOL=$VPN_PROTOCOL
PIA_PF=$PIA_PF
DISABLE_IPV6=$DISABLE_IPV6
PREFERRED_REGION=$PREFERRED_REGION
PIA_DNS=$PIA_DNS
DIP_TOKEN=$DIP_TOKEN
EOF

echo "options.env created successfully:"
cat "$OPTIONS_FILE"